### ISSUE TITLE
Design a logo for the project

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/webworkbook#13]
Here is the proposed logo for the project:

![logov2](https://user-images.githubusercontent.com/10350960/192028640-e0e0f6a6-0cd7-4153-be77-feb364044610.png)

**Comment by bpires** [comment]
LGTM! 🎉

**Comment by zoe-moment** [comment]
Are we planning on making this logo an SVG?

**Comment by schalkneethling** [comment]
> Are we planning on making this logo an SVG?

Yes! I am going to upload all the source assets to the web://workbook repo.
