### ISSUE TITLE
Define color scheme

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/webworkbook#15]
Define the color palette based on the colors used in the logo.

**Comment by schalkneethling** [comment]
The proposed color palette is on Figma: 
https://www.figma.com/file/Ys8nhLVI00OxRfnf02MmLs/brand-and-web-presence?node-id=1%3A2

Here is also a screenshot

![Screenshot of the proposed color palette linked above](https://user-images.githubusercontent.com/10350960/192059197-4207f9c6-6d7e-4ab5-9cfe-d6e2a6e6d604.png)

**Comment by KobayashiComputing** [comment]
That looks fine to me, but remember: I'm not a designer. My sense of aesthetics is sorely lacking.

**Comment by bpires** [comment]
I'm getting a "File not found" on the link, but based on the screenshot, it looks great to me! The base palette, especially, I think it's a solid one. 

I didn't get the "C-lots-of-numbers" meaning on the bottom 😅 pardon my lack of experience with design systems.

**Comment by schalkneethling** [comment]
> I didn't get the "C-lots-of-numbers" meaning on the bottom 😅 pardon my lack of experience with design systems.

Those indicate the contrast ratio between the colors.

**Comment by schalkneethling** [comment]
> I'm getting a "File not found" on the link

Meh, I will migrate that into PenPot

**Comment by zoe-moment** [comment]
As this issue is open is it okay if I migrate the color scheme into PenPot? I haven't contributed yet so I'm still working out how this all goes down.

**Comment by bpires** [comment]
It'll be good to have a design system in place (with a comprehensive style guide), and we can provide feedback asynchronously with the PenPot's comment tool.

**Comment by schalkneethling** [comment]
> As this issue is open is it okay if I migrate the color scheme into PenPot? I haven't contributed yet so I'm still working out how this all goes down.

I completely missed this, my apologies. I am not sure if I had done it before or after, but the colour palette does exist in Penpot.

![Xnapper-2022-10-22-15 08 20](https://user-images.githubusercontent.com/10350960/197340855-524e2f9d-97cb-4bc9-a8f9-5b2747e2d44b.png)

With that, I am going to close out the issue. Feel free to provide additional feedback via Penpot or Discord. Thanks!
