### ISSUE TITLE
Define typography

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/webworkbook#16]
Define the typographic scale to use for the project and the typeface we will use.

- https://type-scale.com/
- I am thinking Roboto for the main content and Roboto Slab for headings

**Comment by schalkneethling** [comment]
Here is a preview of the typography: https://type-scale.com/?size=16&scale=1.250&text=A%20Visual%20Type%20Scale&font=Roboto%20Slab&fontweight=800&bodyfont=Roboto&bodyfontweight=400&lineheight=1.75&backgroundcolor=%23ffffff&fontcolor=%23202020&preview=true

Below is also a screenshot:

![Screenshot showing the text The Mycelium Network at different font sizes](https://user-images.githubusercontent.com/10350960/192097031-245e3f0f-feed-4e4d-9732-212129e05598.png)

On Figma: https://www.figma.com/file/Ys8nhLVI00OxRfnf02MmLs/brand-and-web-presence?node-id=1%3A2

**Comment by KobayashiComputing** [comment]
It is a bit disconcerting to me that the "T" in the word "The" is noticeably shorter than the "h" which is right beside it. It's not as noticeable in the serif version (I think that's the correct term for the first 4, more bold lines), but I can also see it in the sans serif version. Just my personal opinion.

**Comment by bpires** [comment]
> It is a bit disconcerting to me that the "T" in the word "The" is noticeably shorter than the "h" which is right beside it. It's not as noticeable in the serif version (I think that's the correct term for the first 4, more bold lines), but I can also see it in the sans serif version. Just my personal opinion.

OMG, once I saw it, I can't unsee it now 🤐 hahah

But I pretty much like Roboto, I use it a lot on my google sheets/docs. The other ones I like are Inter and Open Sans. I guess it's a good call to mix the Roboto slab for titles and the regular roboto for the text.

**Comment by schalkneethling** [comment]
@KobayashiComputing, @bpires, @zoe-moment I updated the typography and scale. You can get an idea of it here:
https://type-scale.com/?size=16&scale=1.333&text=web%3A%2F%2Fworkbook&font=Raleway&fontweight=800&bodyfont=Domine&bodyfontweight=400&lineheight=1.5&backgroundcolor=%23ffffff&fontcolor=%23212121&preview=false

**Comment by KobayashiComputing** [comment]
That looks much better to me. The lowercase ascenders are still very slightly taller than the uppercase letters, but not as noticeable as with the Roboto font. Also, I do like the look of it overall, and  even down to the .422 rem it was easily readable on my mobile phone (iPhone 11 Pro, if it makes a difference). Unless someone has a strong objection or a better suggestion, I vote for this one.

**Comment by schalkneethling** [comment]
Thank you for the feedback, @KobayashiComputing. I did rethink my choice and did my research this time. I do believe these will be much more readable.

**Comment by schalkneethling** [comment]
Hey all,

While working on the design in Penpot, I realized the default typographic scale is too big for mobile, so I am creating a secondary scale for mobile. When designing, use the `--typography-size...` for desktop and the `--typography-mobile-size...` for mobile.
