### ISSUE TITLE
Define iconography

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/webworkbook#17]
It is essential that any iconography we use is consistent so, it would be good to choose a library to use for our iconography. It is also a must that the icons are available as SVG and not an icon font.

**Comment by bpires** [comment]
I guess you have a better background with it, but here are some resources I've found on a quick search.

I'll explore more to give a proper review on some of them.

https://primer.style/octicons/

https://remixicon.com/

https://ionic.io/ionicons

https://feathericons.com/

https://akveo.github.io/eva-icons/#/

https://heroicons.com/

https://icons.getbootstrap.com/

https://ikonate.com/

**Comment by schalkneethling** [comment]
> https://primer.style/octicons/

I am leaning heavily towards Octicons.

**Comment by bpires** [comment]
> I am leaning heavily towards Octicons.

I second that! I like the style, it's open source, and it's market validated.

**Comment by schalkneethling** [comment]
I was looking at Octicons, and I believe we might need a backup for some icons that Octicons do not have. I am going to double-check, but I think Bootstrap icons will fit well with Octicons in terms of style.

**Comment by schalkneethling** [comment]
For iconography needs, we will use:

- https://primer.style/octicons/ - if you cannot find an icon here, fallback to,
- https://icons.getbootstrap.com/
