### ISSUE TITLE
Document internet protocols

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/webworkbook#24]
Refer to the protocols section of the Miro board here:
https://miro.com/app/board/uXjVPR_kJsM=/

When writing content, try to focus on writing a synopsis and linking to the content for further reading.
For videos, feel free to use Hugo shortcodes to embed the video in context.

https://gohugo.io/content-management/shortcodes/#use-hugos-built-in-shortcodes

The page to update is:
https://github.com/The-Mycelium-Network/webworkbook/tree/main/content/topics/what-is-the-internet

**Comment by Rico-Smit** [comment]
I will be committing the first change today to add the protocol file and index.md

**Comment by Rico-Smit** [comment]
@carinadiesel-dev will be helping with the HTTP - HTTPS protocol.
