### ISSUE TITLE
[TRACKER] Improve documentation: contributing guidelines

### ISSUE THREAD

**Issue by bpires** [The-Mycelium-Network/webworkbook#72]
As a beginner-friendly project, I realized we should have more detailed guidelines for project contributions. 

This will be useful for people who weren't following the discussions from the start or are not entirely familiar with the project structure or the tools used.

Topics to include:

- [ ] #76
- [ ] #77
- [ ] #78
- [ ] #79
- [ ] #80
- [ ] #81
- [ ] ...

**Comment by schalkneethling** [comment]
This is great! Thanks for opening this issue. I am going to bump the importance of this one.

**Comment by schalkneethling** [comment]
@bpires I have spun off issues for each of the to-do items in the list. We can use this issue as a tracker.

**Comment by schalkneethling** [comment]
@bpires, I will close this one, and then we can focus on the individual issues I created. Thanks again for starting the conversation.
